const $=s=>document.querySelector(s);
const pref={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
let lang='en';
let theme=pref.get('da-theme')||'light';let filter='All';let detectedCountry=null;let detectedRegion='';let detectedZone=null;
let activeArt=0;let activePiece=0;let viewerItems=[];let artZoom=false;let artOpener=null;
const t=(es,en)=>lang==='es'?es:en;
const intro=()=>t('Soy diseñador gráfico enfocado en publicidad, branding, desarrollo web y motion graphics. Tengo tres años de experiencia en diseño gráfico, identidad de marca y campañas de marketing. Me apasiona explorar ideas y cuidar los detalles de cada proyecto.','I’m a graphic designer focused on advertising, branding, web development, and motion graphics. I have three years of hands-on experience in graphic design, brand identity, and marketing campaigns. I enjoy exploring ideas and bringing attention to detail to every project.');
const chips=()=>'<div class="disciplines"><span>Branding</span><span>'+t('Publicidad','Advertising')+'</span><span>Social Media</span><span>'+t('Ilustración','Illustration')+'</span><span>Motion</span><span>Editorial</span></div>';
const home=()=>`<section class="home"><div class="intro"><span class="eyebrow">${t('Portafolio / 2026','Portfolio / 2026')}</span><h1>Diego<span>Alvarez.</span></h1><p class="description">${intro()}</p>${chips()}<div class="intro-bottom"><div class="home-actions"><a class="pill primary" href="#work">${t('Ver proyectos','View work')} ↗</a><a class="pill" href="#about">${t('Sobre mí / CV','About / CV')} ↓</a></div><span class="location">Nuevo León, ${t('México','Mexico')}</span></div></div><div class="photo-space"><img class="portrait" src="assets/FotoCV.png" alt="${t('Retrato de Diego Alvarez','Portrait of Diego Alvarez')}" width="1122" height="1402"></div></section>`;
const categoryName=c=>c==='Illustration'?t('Ilustración','Illustration'):c==='Advertising'?t('Publicidad','Advertising'):c;
const assetUrl=src=>src.split('/').map(encodeURIComponent).join('/');
const work=()=>`<section class="page work-page"><span class="eyebrow">01 / ${t('Selección de trabajos','Selected work')}</span><h1>${t('Proyectos','Work')}.</h1><div class="filters" aria-label="${t('Categorías','Categories')}">${['All','Branding','Advertising','Social Media','Illustration','Motion','Editorial'].map(x=>`<button data-filter="${x}" aria-pressed="${filter===x}">${x==='All'?t('Todos','All'):categoryName(x)}</button>`).join('')}</div><div class="art-grid">${window.DA_PROJECTS.map((item,i)=>({item,i})).filter(({item})=>filter==='All'||item.category===filter).map(({item,i},n)=>`<${item.type==='pdf'&&location.protocol==='file:'?'a':'button'} class="art-card" ${item.type==='pdf'&&location.protocol==='file:'?`href="${assetUrl(item.src)}" target="_blank" rel="noopener"`:`data-art="${i}"`} aria-label="${t('Abrir: ','Open: ')+t(item.titleEs,item.titleEn)}"><span class="art-thumb">${item.type==='video'?`<video class="motion-thumb" src="${assetUrl(item.src)}#t=0.1" preload="metadata" muted playsinline aria-hidden="true"></video><span class="motion-play" aria-hidden="true">▶</span>`:`<img src="${assetUrl(item.cover||item.displaySrc||item.src)}" alt="${t(item.titleEs,item.titleEn)}" loading="${n<2?'eager':'lazy'}" decoding="async">`}${item.type==='case'?`<span class="project-badge">${item.slug==='logofolio'?t('Selección','Collection'):t('Ver proyecto','View project')}</span>`:item.type==='pdf'?`<span class="project-badge">PDF · ${item.pages} ${t('pág.','pp.')}</span>`:item.images.length>1?`<span class="project-badge">${item.images.length} ${t('piezas','pieces')}</span>`:''}</span><span class="art-caption"><span>${t(item.titleEs,item.titleEn)}</span><span class="art-category">${categoryName(item.category)} <span aria-hidden="true">↗</span></span></span></${item.type==='pdf'&&location.protocol==='file:'?'a':'button'}>`).join('')}</div>${window.DA_PROJECTS.some(p=>filter==='All'||p.category===filter)?'':`<div class="empty"><h2>${t('Próximamente','Coming soon')}</h2><p>${t('Los proyectos de esta categoría se incorporarán más adelante.','Projects in this category will be added soon.')}</p></div>`}</section>`;

const about=()=>`<section class="page"><span class="eyebrow">02 / ${t('Mi perfil','My profile')}</span><h1>${t('Sobre mí','About')}.</h1><p class="about-copy">${intro()}</p><div class="about-grid"><div><h2>${t('Experiencia','Experience')}</h2>${[['TEKTON LABS',t('Diseñador gráfico','Graphic Designer'),t('Noviembre de 2025 — Enero de 2026','November 2025 — January 2026')],['SELVATICO',t('Especialista en diseño gráfico','Graphic Design Specialist'),t('Agosto — Noviembre de 2025','August — November 2025')],['DANFOSS',t('Practicante de marketing y diseño gráfico','Marketing & Graphic Design Intern'),t('Agosto de 2023 — Julio de 2025','August 2023 — July 2025')],['PAPALOTE MUSEO DEL NIÑO',t('Mediador','Museum Facilitator'),t('Diciembre de 2024 — Mayo de 2025','December 2024 — May 2025')]].map(j=>`<div class="job"><strong>${j[0]}</strong><span>${j[1]}<br>${j[2]}</span></div>`).join('')}</div><div><h2>${t('Herramientas','Tools')}</h2><div class="tools">${['Photoshop','Illustrator','After Effects','Premiere','InDesign','Figma','DaVinci Studio','Canva','MS Office',t('Herramientas de IA','AI tools')].map(x=>`<span>${x}</span>`).join('')}</div><h2>${t('Idiomas','Languages')}</h2><p class="about-copy">${t('Español · Nativo<br>Inglés · C1 (Avanzado)<br>Francés · A1 (Básico)','Spanish · Native<br>English · C1 (Advanced)<br>French · A1 (Basic)')}</p><a class="pill" href="assets/Diego_Alvarez_CV_2026.pdf" target="_blank" rel="noopener">${t('Ver CV','View CV')} ↗</a></div></div></section>`;
const services=()=>`<section class="page services-page"><span class="eyebrow">03 / ${t('Cómo puedo ayudarte','What I can do for you')}</span><h1>${t('Servicios','Services')}.</h1><p class="about-copy">${t('Diseño para marcas, contenido y proyectos que necesitan una identidad visual clara.','Design for brands, content, and projects that need a clear visual identity.')}</p><div class="service-list">${[
 ['Branding',t('Identidad con intención.','Identity with intention.'),t('Logotipos, sistemas visuales y manuales de identidad para dar consistencia a tu marca.','Logos, visual systems, and brand guidelines to give your brand a consistent identity.'),'Logotipo · Identidad · Manual'],
 [t('Publicidad','Advertising'),t('Ideas que conectan.','Ideas that connect.'),t('Diseño de anuncios y piezas gráficas para campañas impresas y digitales.','Ad design and visual assets for print and digital campaigns.'),''],
 ['Social Media',t('Contenido que comunica.','Content that communicates.'),t('Diseño de publicaciones, carruseles y piezas para campañas digitales, alineadas con la identidad de tu marca.','Posts, carousels, and digital campaign assets aligned with your brand identity.'),'Posts · Carruseles · Campañas'],
 [t('Ilustración','Illustration'),t('Ideas con personalidad.','Ideas with personality.'),t('Ilustraciones digitales para proyectos editoriales, publicidad y contenido visual.','Digital illustrations for editorial projects, advertising, and visual content.'),'Digital · Editorial · Conceptual'],
 ['Motion',t('Diseño en movimiento.','Design in motion.'),t('Animación gráfica y piezas audiovisuales breves para comunicar ideas, productos y marcas.','Motion graphics and short audiovisual pieces to communicate ideas, products, and brands.'),'Animación · Video · Motion'],
 ['Editorial',t('Cada página cuenta.','Every page matters.'),t('Diseño y maquetación de manuales, catálogos y documentos con una estructura clara y cuidada.','Design and layout of manuals, catalogs, and documents with a clear, considered structure.'),'Manuales · Catálogos · PDF']
 ].map((x,i)=>`<article class="service-item"><span class="service-number">0${i+1}</span><div><h2>${x[0]}</h2><h3>${x[1]}</h3><p>${x[2]}</p></div><a href="#contact" class="service-link" aria-label="${t('Consultar sobre ','Ask about ')+x[0]}">↗</a></article>`).join('')}</div><a class="pill primary" href="#contact">${t('Cuéntame tu proyecto','Tell me about your project')}</a></section>`;
const contact=()=>`<section class="page"><span class="eyebrow">04 / ${t('Hablemos','Get in touch')}</span><h1>${t('Contacto','Contact')}.</h1><form class="form"><label for="name">${t('Nombre','Name')}</label><input id="name" name="name" autocomplete="name" required maxlength="100"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="200"><label for="message">${t('Mensaje','Message')}</label><textarea id="message" name="message" required maxlength="4000"></textarea><button class="pill primary" type="submit">${t('Enviar','Send')}</button><p class="form-note">${t('En esta vista previa, se abrirá tu aplicación de correo con el mensaje preparado.','In this preview, your email application will open with your message ready to send.')}</p><p class="form-note" role="status" id="status"></p></form></section>`;
function countryLabel(){
 const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 const code=detectedCountry||window.DA_ZONE_COUNTRIES?.[zone];
 if(code){try{return new Intl.DisplayNames([lang],{type:'region'}).of(code)}catch{}}
 return t('Hora local','Local time');
}
function regionLabel(){
 const mx={AGU:'Aguascalientes',BCN:'Baja California',BCS:'Baja California Sur',CAM:'Campeche',CHP:'Chiapas',CHH:'Chihuahua',CMX:'Ciudad de México',COA:'Coahuila',COL:'Colima',DUR:'Durango',GUA:'Guanajuato',GRO:'Guerrero',HID:'Hidalgo',JAL:'Jalisco',MEX:'Estado de México',MIC:'Michoacán',MOR:'Morelos',NAY:'Nayarit',NLE:'Nuevo León',NL:'Nuevo León',OAX:'Oaxaca',PUE:'Puebla',QUE:'Querétaro',ROO:'Quintana Roo',SLP:'San Luis Potosí',SIN:'Sinaloa',SON:'Sonora',TAB:'Tabasco',TAM:'Tamaulipas',TLA:'Tlaxcala',VER:'Veracruz',YUC:'Yucatán',ZAC:'Zacatecas'};
 return detectedCountry==='MX'?(mx[detectedRegion.replace(/^MX-/, '')]||detectedRegion):detectedRegion;
}
function updateClock(){
 const options={hour:'2-digit',minute:'2-digit',hour12:true};if(detectedZone)options.timeZone=detectedZone;
 const value=new Intl.DateTimeFormat('en-US',options).format(new Date());
 const locationLabel=[regionLabel(),countryLabel()].filter(Boolean).join(', ');
 $('time').textContent=value;$('.country-label').textContent=locationLabel;
 $('.clock').title=detectedZone?t('Ubicación aproximada según tu conexión; hora de esa zona','Approximate location from your connection; time in that zone'):t('Ubicación aproximada; hora del dispositivo mientras no se conozca la zona','Approximate location; device time when the time zone is unavailable');
 $('.footer-clock').textContent=locationLabel+' · '+value;$('.footer-clock').title=$('.clock').title;
}

function render(){const requested=location.hash==='#cv'?'about':location.hash.slice(1)||'home';const caseItem=window.DA_PROJECTS.find(p=>p.type==='case'&&requested==='case-'+p.slug);const page=caseItem?'work':['home','work','about','services','contact'].includes(requested)?requested:'home';document.body.dataset.page=page;document.documentElement.lang=lang;$('.brand').setAttribute('aria-label',t('Diego Alvarez — Inicio','Diego Alvarez — Home'));$('nav').setAttribute('aria-label',t('Principal','Main navigation'));$('.skip').textContent=t('Saltar al contenido','Skip to content');document.documentElement.dataset.theme=theme;updateTheme();$('#main').innerHTML=caseItem?window.caseContent(caseItem):({home,work,about,services,contact}[page])();if(caseItem)window.bindCase(caseItem);document.querySelectorAll('[data-es]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('.language span:not(.muted)').forEach(el=>el.className=el.textContent.toLowerCase()===lang?'active':'inactive');$('.theme').setAttribute('aria-label',t('Cambiar a modo ','Switch to ')+(theme==='light'?t('oscuro','dark mode'):t('claro','light mode')));$('.language').setAttribute('aria-label',t('Switch to English','Cambiar a español'));document.querySelectorAll('.nav-card').forEach(el=>{if(el.hash==='#'+page){el.setAttribute('aria-current','page');el.querySelector('.arrow').textContent='→'}else{el.removeAttribute('aria-current');el.querySelector('.arrow').textContent='↗'}});document.querySelectorAll('[data-filter]').forEach(el=>el.onclick=()=>{filter=el.dataset.filter;render()});document.querySelectorAll('[data-art]').forEach(el=>el.onclick=()=>{artOpener=el;const index=Number(el.dataset.art);if(window.DA_PROJECTS[index].type==='case')location.hash='case-'+window.DA_PROJECTS[index].slug;else if(window.DA_PROJECTS[index].type==='pdf')window.openBook(index);else if(window.DA_PROJECTS[index].type==='video')window.openMotion(index);else openArt(index)});const form=$('form');if(form)form.onsubmit=e=>{e.preventDefault();const data=new FormData(form);const body=`${data.get('message')}\n\n${data.get('name')}\n${data.get('email')}`;location.href='mailto:diegoalvarezg04@gmail.com?subject='+encodeURIComponent(t('Contacto desde el portafolio — ','Portfolio enquiry — ')+data.get('name'))+'&body='+encodeURIComponent(body);$('#status').textContent=t('Confirma el envío desde tu aplicación de correo. Si no se abre, escribe a diegoalvarezg04@gmail.com.','Complete sending in your email app. If it does not open, write to diegoalvarezg04@gmail.com.');};$('#year').textContent=new Date().getFullYear();updateClock();}
$('.language').onclick=()=>{lang=lang==='es'?'en':'es';pref.set('da-language',lang);render()};$('.theme').onclick=()=>{theme=theme==='light'?'dark':'light';pref.set('da-theme',theme);document.documentElement.dataset.theme=theme;updateTheme()};addEventListener('hashchange',()=>{render();$('#main').scrollTo({top:0,behavior:'instant'});window.scrollTo({top:0,behavior:'instant'});$('#main').focus({preventScroll:true})});render();setInterval(updateClock,1000);

function updateTheme(){const dark=theme==='dark';$('.theme').innerHTML=dark?'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4.2 4.2l2.1 2.1m11.4 11.4 2.1 2.1M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"/></svg>':'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M20.5 14A9 9 0 0 1 10 3.5 9 9 0 1 0 20.5 14Z"/></svg>';$('.theme').setAttribute('aria-label',t('Cambiar a modo ','Switch to ')+(dark?t('claro','light mode'):t('oscuro','dark mode')))}
updateTheme();

async function detectCountry(){
 const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),4500);
 try{const response=await fetch('https://api.country.is/?fields=subdivision,location',{signal:controller.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!response.ok)return;const data=await response.json();if(typeof data.country==='string'&&/^[A-Z]{2}$/.test(data.country)){detectedCountry=data.country;detectedRegion=typeof data.subdivision==='string'?data.subdivision.slice(0,80):'';if(typeof data.location?.time_zone==='string'){try{new Intl.DateTimeFormat('en',{timeZone:data.location.time_zone}).format();detectedZone=data.location.time_zone}catch{}}updateClock();}}
 catch{/* Keep the time-zone estimate, or local-time label when unknown. */}
 finally{clearTimeout(timeout);}
}
detectCountry();

function artContent(){const piece=viewerItems[activePiece];const item=piece.project;return `<div class="art-viewer-shell"><div class="art-toolbar"><span>${categoryName(item.category)} · ${String(activePiece+1).padStart(2,'0')} / ${String(viewerItems.length).padStart(2,'0')}</span><div><button data-view-action="zoom" aria-label="${t('Alternar ampliación','Toggle zoom')}" aria-pressed="${artZoom}">${window.viewerIcon(artZoom?'minus':'plus')}</button><button data-view-action="close" aria-label="${t('Cerrar','Close')}">${window.viewerIcon('close')}</button></div></div><div class="art-stage ${artZoom?'zoomed':''}"><img src="${assetUrl(piece.display||piece.src)}" alt="${t(item.titleEs,item.titleEn)}"></div><div class="art-details"><div><h2 id="art-title">${t(item.titleEs,item.titleEn)}</h2><p>${t(item.descriptionEs,item.descriptionEn)}</p><a class="original-link" href="${assetUrl(piece.src)}" target="_blank" rel="noopener">${t('Abrir original','Open original')}</a></div><div class="art-pagination"><button data-view-action="previous" aria-label="${t('Imagen anterior','Previous image')}">${window.viewerIcon('prev')}</button><button data-view-action="next" aria-label="${t('Siguiente imagen','Next image')}">${window.viewerIcon('next')}</button></div></div></div>`}
function paintArt(){artZoom=false;const dialog=$('#art-viewer');dialog.innerHTML=artContent();if(!dialog.open){dialog.showModal();window.animateViewerOpen(dialog);document.body.classList.add('viewer-open')}dialog.querySelector('[data-view-action="close"]').focus()}
function openArt(index){activeArt=index;const item=window.DA_PROJECTS[index];viewerItems=item.category==='Illustration'?window.DA_PROJECTS.filter(p=>p.category==='Illustration').map(p=>({project:p,src:p.src,display:p.displaySrc})):item.images.map((src,i)=>({project:item,src,display:item.displayImages?.[i]}));activePiece=Math.max(0,viewerItems.findIndex(p=>p.src===item.src));paintArt()}
function stepArt(step){activePiece=(activePiece+step+viewerItems.length)%viewerItems.length;paintArt()}
function closeArt(){window.closeViewer($('#art-viewer'))}
$('#art-viewer').addEventListener('close',()=>{document.body.classList.remove('viewer-open');if(artOpener?.isConnected)artOpener.focus({preventScroll:true})});
$('#art-viewer').addEventListener('click',e=>{const action=e.target.closest('[data-view-action]')?.dataset.viewAction;if(action==='close'||e.target===$('#art-viewer'))closeArt();if(action==='next')stepArt(1);if(action==='previous')stepArt(-1);if(action==='zoom'){artZoom=!artZoom;$('#art-viewer .art-stage').classList.toggle('zoomed',artZoom);const button=e.target.closest('button');button.innerHTML=window.viewerIcon(artZoom?'minus':'plus');button.setAttribute('aria-pressed',String(artZoom))}});
$('#art-viewer').addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();stepArt(1)}if(e.key==='ArrowLeft'){e.preventDefault();stepArt(-1)}});
let swipeStart=null;
$('#art-viewer').addEventListener('touchstart',e=>{swipeStart=e.touches.length===1?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null},{passive:true});
$('#art-viewer').addEventListener('touchend',e=>{if(swipeStart&&!artZoom){const dx=e.changedTouches[0].clientX-swipeStart.x;const dy=e.changedTouches[0].clientY-swipeStart.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)stepArt(dx<0?1:-1)}swipeStart=null},{passive:true});

$('#art-viewer').addEventListener('cancel',e=>{e.preventDefault();closeArt()});
